# Generated by Django 5.2 on 2025-11-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_comentariocontacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentariocontacto',
            options={'ordering': ['-created'], 'verbose_name': 'Comentario Contacto', 'verbose_name_plural': 'Comentarios Contactos'},
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
